spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newsdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
    com.news: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

openai:
  api-key: {YOUR KEY}
  model: openai/gpt-3.5-turbo
  base-url: https://openrouter.ai/api/v1